export { default as Body } from './Body'
export { default as Calipers } from './Calipers'
export { default as Glasses } from './Glasses'
export { default as Interior } from './Interior'
export { default as Logo } from './Logo'
export { default as Rim1 } from './Rim1'
export { default as Rim2 } from './Rim2'
export { default as Rim3 } from './Rim3'