export { default as Body } from './Body';
export { default as BrakeDisc } from './BrakeDisc';
export { default as Calipers } from './Calipers';
export { default as Exhaust } from './Exhaust';
export { default as ExhaustCover } from './ExhaustCover';
export { default as Frame } from './Frame';
export { default as HeadlightGlasses } from './HeadlightGlasses';
export { default as Headlights } from './HeadLights'
export { default as Logos } from './Logos';
export { default as NumberPlate } from './NumberPlate';
export { default as Rim1 } from './Rim1';
export { default as Rim2 } from './Rim2';
export { default as Rim3 } from './Rim3';
export { default as TailLights } from './TailLights'
export { default as Tyre } from './Tyre';
export { default as UnderTray } from './UnderTray';
export { default as Window } from './Window'